ktor {
  development = false
  deployment {
    port = 8080
    port = ${?PORT}
    watch = [classes, resources]
  }
  application {
    modules = [
      com.example.MainKt.module
    ]
  }
}

aws {
  dynamodb {
    // 1. Default base value, THEN environmental override below it
    tableName = "urls"
    tableName = ${?DYNAMO_TABLE_NAME}

    region = "us-east-1"
    region = ${?AWS_REGION}

    endpoint = "http://localhost:8000"
    endpoint = ${?DYNAMODB_ENDPOINT}
  }
}