ktor {
  deployment {
    port = 8080
    port = ${?PORT}
  }
  application {
    modules = [
      com.example.SerializationKt.configureSerialization
      com.example.KoinKt.configureKoin
      com.example.StatusPagesKt.configureStatusPages
      com.example.RoutingKt.configureRouting
    ]
  }
}