ktor {
  development = false
  deployment {
    port = 8080
    port = ${?PORT}
    watch = [classes, resources]
  }
  application {
    modules = [
      com.example.MainKt.module
    ]
  }
}

aws {
  dynamodb {
    // 1. Default base value, THEN environmental override below it
    tableName = "UrlMappings"
    tableName = ${?DYNAMO_TABLE_NAME}

    region = "eu-west-2"
    region = ${?AWS_REGION}

    #DO NOT set endpoint = "http://localhost:8000" here.
    # Use optional substitution so it is null if DYNAMODB_ENDPOINT isn't defined:
    endpoint = ${?DYNAMODB_ENDPOINT}
  }
}